title: Earth Science Data Analylytics
desctiption: Class portfolio
logo: img/LC overhanging wal-tree.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
